#!/usr/bin/env python3
# SPDX-FileCopyrightText: © 2026 Tenstorrent Inc.
# SPDX-License-Identifier: Apache-2.0
"""
bench_brown_repro.py — N = 16384 hero replication (Brown 2025 Table 1).

Brown et al. "Fast Fourier Transforms on Tenstorrent Wormhole" (2025)
report sustained throughput numbers for N = 16384, batch = 1, fp32.
This script reproduces that exact setup with our ttnn op and writes:

    * paper_results/csv/brown_repro.csv
    * paper_results/figs/table_brown.tex   — drop-in LaTeX fragment

CSV columns:
    N, dtype, precision, batch, median_us, gflops, rel_err
"""
from __future__ import annotations

import sys
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _common as C
import ttnn


N_HERO = 16384
BATCH = 1
ITERS = 200
WARMUP = 10


def main() -> int:
    p = C.base_argparser(__doc__ or "")
    p.set_defaults(N=str(N_HERO), batch=str(BATCH),
                   iters=ITERS, warmup=WARMUP)
    args = p.parse_args()

    dtypes = C.parse_dtype_list(args.dtype)

    out_path = Path(args.out) if args.out else C.default_out_path("brown_repro")
    writer = C.CsvWriter(out_path, [
        "N", "dtype", "precision", "batch", "median_us", "gflops", "rel_err",
    ])

    rows: list[dict] = []

    with C.open_device() as device:
        for dtype in dtypes:
            precisions = C.parse_precision_list(args.precision, dtype)
            for prec in precisions:
                tt_in, torch_in = C.make_input(
                    N_HERO, BATCH, dtype, device, seed=args.seed)

                def call():
                    C.call_fft(tt_in, precision=prec)

                stats = C.time_call_us(
                    call, device, warmup=args.warmup, iters=args.iters)
                gf = C.gflops(N_HERO, BATCH, stats["median_us"] / 1e6)

                re_tt, im_tt = ttnn.experimental.fft(tt_in, precision=prec)
                got = C.tt_output_as_complex(re_tt, im_tt)
                ref = C.torch_ref_fft(torch_in)
                err = C.rel_err_complex(got.reshape(ref.shape), ref)

                row = {
                    "N": N_HERO, "dtype": dtype, "precision": prec,
                    "batch": BATCH,
                    "median_us": f"{stats['median_us']:.3f}",
                    "gflops": f"{gf:.3f}",
                    "rel_err": f"{err:.3e}",
                }
                rows.append(row)
                writer.write(row)
                C.log(
                    f"N={N_HERO} {dtype}/{prec:>7}: "
                    f"med={stats['median_us']:.1f}us  "
                    f"gflops={gf:.2f}  rel_err={err:.2e}")
                C.cleanup()

    writer.close()
    _emit_latex(rows, out_path.parent.parent / "figs" / "table_brown.tex")
    C.log(f"Wrote {out_path}")
    return 0


def _emit_latex(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as fh:
        fh.write(r"""% Auto-generated by bench_brown_repro.py — do not hand-edit.
\begin{tabular}{lcrrr}
\toprule
dtype & precision & median ($\mu$s) & GFLOP/s & rel.\ err \\
\midrule
""")
        for r in rows:
            fh.write(
                f"  {r['dtype']} & {r['precision']} & "
                f"{r['median_us']} & {r['gflops']} & {r['rel_err']} \\\\\n"
            )
        fh.write(r"""\bottomrule
\end{tabular}
""")
    C.log(f"Wrote {path}")


if __name__ == "__main__":
    raise SystemExit(main())
